from fast_food import *
import time as t
maria = Cashier("Maria",12346,15,18)
maria.clock_in()
maria.clock_out()
maria.get_pay()
maria.add_transaction()
dave = Cleaner("Dave",12345,15,18,"Kitchen")
dave.clock_out()
dave.get_pay()
dave.check_area()
nathan  = Cook("Nathan",12465,12,20)
nathan.clock_in()
nathan.clock_out()
nathan.get_pay()
nathan.add_meal()
max = drive_thru_Cashier("Max",1234565,20,13,"1")
max.clock_in()
max.clock_out()
max.get_pay()
max.check_lane()